### ISSUE TITLE
Bulls and Cows - 숫자 입력 함수 구현

### ISSUE THREAD

**Issue by JongDo737** [ktc-fe3/practice-gitflow#4]
## Description
숫자 입력 함수 생성

## Tasks

- [x] 입력 함수 생성
- [x] 숫자 인지 체크
- [x] 4자리 수인지 체크

## References

-[Bulls and Cows][https://www.mathsisfun.com/games/bulls-and-cows.html]
